# Generated by Django 3.2.6 on 2021-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_auto_20210815_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': "Author's Address", 'verbose_name_plural': 'Address Entries'},
        ),
        migrations.AddField(
            model_name='book',
            name='issued_library',
            field=models.ManyToManyField(to='book_outlet.Library'),
        ),
    ]
